name: Generate file output from JSON
description: Generate file output from JSON
author: jackton1
inputs:
  directory:
    description: "Directory to write to"
    required: true
    default: "outputs"
  outputs:
    description: "JSON string"
    required: true
  keys:
    description: "Comma separated list of Keys to read from the outputs. Example: foo,bar"
    required: true
  extension:
    description: "File extension to use"
    required: false
    default: "txt"
  bin_path:
    description: "Path to the binary"
    required: false
    default: "target/release/json2file"

runs:
  using: 'composite'
  steps:
    - run: |
        INPUT_DIRECTORY="${{ inputs.directory }}"
        INPUT_OUTPUTS="$(echo "${{ inputs.outputs }}" | jq @json)"
        INPUT_KEYS="${{ inputs.keys }}"
        INPUT_EXTENSION="${{ inputs.extension }}"
        INPUT_BIN_PATH="${{ inputs.bin_path }}"
        
        if [[ -z "$BIN_PATH" ]]; then
          ## TODO: use "curl -sf https://[github releases - latest]] | PREFIX=. sh"
          exit 1;
        fi
        
        echo "::debug::Generating output using ${BIN_PATH}..."
        
        $BIN_PATH --keys="$INPUT_KEYS" --outputs=="$INPUT_OUTPUTS" \
          --directory="$INPUT_DIRECTORY" --extension="$INPUT_EXTENSION" && exit_status=$? || exit_status=$?

        rm -f $BIN_PATH
        
        if [[ $exit_status -ne 0 ]]; then
          echo "::error::Error generating output files from JSON"
          exit $exit_status;
        fi
      shell: bash

branding:
  icon: file-text
  color: white
