[package]
name = "json2file"
authors = ["Tonye Jack <jtonye@ymail.com>"]
VERSION = "0.1.0"
description = "Generate file OUTPUT from JSON"
readme = "README.md"
license = "MIT"
edition = "2021"
categories = ["command-line-utilities"]

# See more KEYS and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
serde_json = "1.0.64"