name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# outputs:
#  added_files:
#    description: "Returns only files that are Added (A)."
#    value: ${{ steps.changed-files.outputs.added_files }}
#  copied_files:
#    description: "Returns only files that are Copied (C)."
#    value: ${{ steps.changed-files.outputs.copied_files }}
#  deleted_files:
#    description: "Returns only files that are Deleted (D)."
#    value: ${{ steps.changed-files.outputs.deleted_files }}
#  modified_files:
#    description: "Returns only files that are Modified (M)."
#    value: ${{ steps.changed-files.outputs.modified_files }}
#  renamed_files:
#    description: "Returns only files that are Renamed (R)."
#    value: ${{ steps.changed-files.outputs.renamed_files }}
#  all_old_new_renamed_files:
#    description:   "Returns only files that are Renamed and list their old and new names. **NOTE:** This requires setting `include_all_old_new_renamed_files` to `true` (R)"
#    value: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
#  type_changed_files:
#    description: "Returns only files that have their file type changed (T)."
#    value: ${{ steps.changed-files.outputs.type_changed_files }}
#  unmerged_files:
#    description: "Returns only files that are Unmerged (U)."
#    value: ${{ steps.changed-files.outputs.unmerged_files }}
#  unknown_files:
#    description: "Returns only files that are Unknown (X)."
#    value: ${{ steps.changed-files.outputs.unknown_files }}
#  all_changed_and_modified_files:
#    description: "Returns all changed and modified files i.e. *a combination of (ACMRDTUX)*"
#    value: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
#  all_changed_files:
#    description: "Returns all changed files i.e. *a combination of all added, copied, modified and renamed files (ACMR)*"
#    value: ${{ steps.changed-files.outputs.all_changed_files }}
#  any_changed:
#    description: "Returns `true` when any of the filenames provided using the `files` input has changed. If no `files` have been specified,an empty string `''` is returned. i.e. *using a combination of all added, copied, modified and renamed files (ACMR)*."
#    value: ${{ steps.changed-files.outputs.any_changed }}
#  only_changed:
#    description: "Returns `true` when only files provided using the `files` input has changed. If no `files` have been specified,an empty string `''` is returned. i.e. *using a combination of all added, copied, modified and renamed files (ACMR)*."
#    value: ${{ steps.changed-files.outputs.only_changed }}
#  other_changed_files:
#    description: "Returns all other changed files not listed in the files input i.e. *using a combination of all added, copied, modified and renamed files (ACMR)*."
#    value: ${{ steps.changed-files.outputs.other_changed_files }}
#  all_modified_files:
#    description: "Returns all changed files i.e. *a combination of all added, copied, modified, renamed and deleted files (ACMRD)*."
#    value: ${{ steps.changed-files.outputs.all_modified_files }}
#  any_modified:
#    description: "Returns `true` when any of the filenames provided using the `files` input has been modified. If no `files` have been specified,an empty string `''` is returned. i.e. *using a combination of all added, copied, modified, renamed, and deleted files (ACMRD)*."
#    value: ${{ steps.changed-files.outputs.any_modified }}
#  only_modified:
#    description: "Returns `true` when only files provided using the `files` input has been modified. If no `files` have been specified,an empty string `''` is returned.(ACMRD)."
#    value: ${{ steps.changed-files.outputs.only_modified }}
#  other_modified_files:
#    description: "Returns all other modified files not listed in the files input i.e. *a  combination of all added, copied, modified, and deleted files (ACMRD)*"
#    value: ${{ steps.changed-files.outputs.other_modified_files }}
#  any_deleted:
#    description: "Returns `true` when any of the filenames provided using the `files` input has been deleted. If no `files` have been specified,an empty string `''` is returned. (D)"
#    value: ${{ steps.changed-files.outputs.any_deleted }}
#  only_deleted:
#    description: "Returns `true` when only files provided using the `files` input has been deleted. If no `files` have been specified,an empty string `''` is returned. (D)"
#    value: ${{ steps.changed-files.outputs.only_deleted }}
#  other_deleted_files:
#    description: "Returns all other deleted files not listed in the files input i.e. *a  combination of all deleted files (D)*"
#    value: ${{ steps.changed-files.outputs.other_deleted_files }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions/setup-rust@v1
      - name: Build binary
        run: cargo build --release
      - name: Run tests
        run: cargo test
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
      - name: Generate output files from JSON
        uses: ./
        with:
          outputs: ${{ steps.changed-files.outputs }};
          keys: |
            added_files
            copied_files
            deleted_files
            modified_files
            renamed_files
            all_old_new_renamed_files
            type_changed_files
            unmerged_files
            unknown_files
            all_changed_and_modified_files
            all_changed_files
            any_changed
            only_changed
            other_changed_files
            all_modified_files
            any_modified
            only_modified
            other_modified_files
            any_deleted
            only_deleted
            other_deleted_files